export interface Account{
    id: string,
    userName: string,
    fullName: string,   
    code: string,
    email: string,
    phoneNumber: string,
    address: string,
    password: string,
    dob: string,
    gender: number,
    roleId: string,
    agencyId: string,
    isDeleted: string,
}